apiVersion: v1
kind: Service
metadata:
  name: evparcial-service
  namespace: evparcial-ns
  labels:
    app: evparcial
spec:
  type: LoadBalancer
  selector:
    app: evparcial
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP